
essen = [
    'einen Wirsingeintopf','einen Lahmacun','eine Portion Kartoffelbrei',
    'Spinat','Astronautenfutter','ein Snickers','einen Mars-Riegel','eine Brezel',
    'eine Portion Gagh','ein Filet Mignon','einen Döner','einen Teller Spaghetti Bolognese',
    'einen Teller Spaghetti mit Käsesahnesoße','einen Obstteller','eine Hand voll Gummibärchen',
    'ein gummiartiges Hühnchen','eine Schale mit Kartoffelchips','zwei Käsebrote',
    'Okonomiyaki','zwei Stück Erdbeertorte','feuriges Chili con Carne','ein fluffiges Rührei',
    'eine leckere Pizza','einen frischen Gurkensalat','einen großen Chefsalat',
    'eine übelriechende Käsesuppe','Fischstäbchen und Kartoffelbrei','ungarisches Gulasch',
    'Spaghetti mit Soja-Bolognese','ein original französisches Ratatouille','einen sahnigen Schokopudding',
    'arme Ritter','einen Festtagsbraten mit Klößen','Pommes mit Majo','leckeren Kartoffelauflauf',
    'Krabben-Cocktail','einen Toast Hawaii','indisches Lamm Curry','einen Gyrosteller mit Tsatsiki',
    'ein Pilz-Risotto','ein hart gekochtes Ei','vier Pralinen mit Nougatfüllung','eine kalte Bockwurst',
    'ein paar Mini-Frühlingsrollen',
    'würziges Kassler mit Sauerkraut','ein Schälchen Apfelmus','Bratkartoffeln','asiatisches Wokgemüse',
    'einen fruchtigen Lolli','einen Teller mit süßem Milchreis','eine Lasagne','chinesisch gebratene Nudeln',
    'ein Thunfisch-Baguette','fünf mexikanische Tacos','einen Blaubeermuffin mit Sahne','eine Hand voll alte Erdnüsse',
    'ein Durianeis am Stiel','eine Mango','einen Erdnussbutterriegel',
    'eine Schachtel Lebkuchen','eine Portion Falafel mit Hummus','ein feuriges Chilli con Soja',
    'einen Teller getrocknete Jackfruchtstücke','eine Packung Choco-Fresh','einen Teller Spaghetti mit Gorgonzolasoße',
    'fein geschnittene Karottenstückchen mit laktosefreiem Frischkäse','ein halbes Grillhuhn',
    'eine Dose Surströmming','einen Steckerlfisch','einen Big King','einen Teller voll Burritos',
    'eine Portion handgerolltes Sushi','ein Butterbrot','eine Schnittlauch Brezel','einen Teller szegediner Gulasch',
    'eine Portion Avocado Maki','eine Spinatlasagne','einen Teller vegetarisch gefüllte Paprika',
    'einen Teller gefüllte Zucchini','ein Schinken-Käse-Omelett','Chop Suey',
    'ein großes Stück Turducken','einen Teller Spaghetti Aglio e Olio','Nudeln mit Pesto',
    'einen Teller Paella','einen Berg Pfannkuchen','einen Teller Belgische Waffeln mit Schokosoße',
    'eine Waffel mit Puderzucker','Grießbrei mit Amarena Kirschen',
    'einen Kaiserschmarrn mit Apfelmus','Palatschinken mit Marillenmarmelade und Staubzucker',
    'eine Tüte Maiswaffeln','eine Packung Schoko Keksi','einen Handkäs mit Musik',
    'eine Schale Grießbrei mit Nutella','ein Gefäß mit Wan Tan',
    'die Reste von gestern','frittierten Tofu auf Eierreis','Kürbiskernbratlinge',
    'eine Handvoll Studentenfutter','ein Schüsselchen Studentenfutter ohne Rosinen',
    'eine Handvoll Knabbersoja','eine Schachtel Pralinen','ein Osternest mit Ostereiern',
    'Räucherspeck mit frischen Zwiebeln','eine große Portion Tortellini mit Frischkäsefüllung',
    'ein rustikales Krustenbrot mit Bergkäse','eine scharfe Salami',
    'Zuckerwatte mit Einhorngeschmack','einen Eimer buntes Popcorn',
    'dampfenden Kaiserschmarrn',
    'Grießbrei mit roter Grütze','brasilianischen Schwarzbohnen-Eintopf (feijoada)',
    'einen ganzen Karpfen mit Gräten','eine abgelehnte Petition',
    'eine dreistöckige Tofu-Turbulenz','eine Kelle kalte Gulaschsuppe',
    'eine Schale tumultuöses Tiramisu','eine leckere frische Hechtsuppe',
    'eine Portion Reispudding','ein Dreierpack Ahoj-Brause',
    'ein feuriges Krabben-Curry','frisches Lammragout',
    'radioaktive Pfifferlinge aus den Prypjatsümpfen','eine Portion zappligen Zucchiniauflauf',
    'einen Teller selbstgedrehte Zucchini-Nudeln',
    'mildes Möhrenmischmasch','gegrillten Kürbis','knusprige Frühlingsrollen mit Dip',
    'drei frische Onigiri','den Kraftriegel der deutschen Arbeiterklasse',
    'Bratwurst mit Sauerkraut','ein Bündel Petersilie',
    'eine Schale Stachelbeerkompott','Stulle mit Brot','einen laienhaft zubereiteten Fugofisch',
    'ein Stück kichernden Käsekuchen mit Himbeeren','eine Handvoll rohe Mandeln',
    'die Rechnung','entzückendes Erbsengemüse','Eierlikörkuchen mit vollständig ausgebackenem Eierlikör',
    'drei Stücke traurige trockene Torte','Wassermelonensalat in einer ausgehöhlten Wassermelone',
    'das feingemahlene Horn eines Narwals','einen Tuppen Gänseschmalz ohne Salz',
    'abgelaufenes Knäckebrot, das nicht mehr knackt',
    'einen runderneuerten Obstkuchen mit upgegradeten Erdbeeren',
    'Rock`n Roll-Rouladen','eine ganze Benjamin-Blümchen-Torte','eine Schüssel chaotische Chili-sin-Carne',
    'eine zerbrochene Schallplatte','sauer eingelegten Aal in Aspik',
    'ein unidentifizierbares Experiment mit zu viel zerlaufener Butter',
    'einen Gruß des Küchenlehrlings',
    'einen Klumpen Teig, der an einen Kuchen erinnert,','gefüllte Chocolate-Chip-Cookies',
    'gedünsteten Brokkoli mit Lachsfilet','gebratenes Gemüse mit Erdnusssoße',
    'einen unleserlicher Brief eines voherigen Besuchers','Quinoasalat mit feinen Tomaten',
    'einen italienischen Klassiker mit einem “Spritzer” Olivenöl',
    'ein selbst gebackenes Kürbiskernbrötchen','ein knuspriges Laugendreieck',
    'eine Wagenladung voll Spritzgebäck','einen Döner mit Mais',
    'eine ominöse grellgrüne Grütze','einen benutzten Teller',
    'Schlagsahne direkt aus der Sprühdose',
    'ein Glas Erdnussbutter und einen Löffel',
    'einen halb gegessenen Pfannkuchen','eine nicht ganz perfekte Crème Brûlée',
    'eine Portion Thunfischsalat','eine rohe Knoblauchzehe',
    'eine Botschaft vom Weihnachtsmann (er wünscht alles Gute)',
    'Wok-Gemüse mit Udonnudeln','eine Schüssel Ramen mit einem Alibi-Ei',
    'eine Kringelbratwurst mit Gurkensalat','ein Stück Lasagne nach einem alten Rezept',
    'die Reliquie eines unbekannten Heiligen','ein Stück Hochzeitstorte mit 2kg Fondant',
    'eine Portion unauthentische vietnamesische Kost','frittiertes Besteck',
    'gut gewürzten Linsensalat','einen Rocula-Wrap mit gehackten Datteln',
    'drei klebrige Ricola-Hustenbonbons','einen von Schnecken zerfressenen Kopfsalat',
    'gedünstete Froschschenkel','heiße Spinatwachteln','eine Portion von Kronks Spinattaschen',
    'ein Steak in Fischform','einen Teller Empörung',
    'Nudeln, die elf Minuten gekocht wurden','ein köstliches Drachenfrucht-Dessert',
    'die Reste der Woche','einen Eimer frittiertes Hühnchen',
    'überbackene Champignons mit Aubergine','eine gefährlich wackelnde Götterspeisetorte',
    'eine Auswahl an Käsesorten mit Weintrauben','eine Schüssel cremige Kürbissuppe',
    'einen dampfenden Gemüsemuffin','eine Scheibe frisches Bananenbrot',
    'eine ordentliche Käsestulle','ein Stück glasierten Zitronenkuchen',
    'einen hübsch verzierten Cupcake','einen drolligen Cake-Pop',
    'eine erfrischende ganze Gurke','ein Lammfilet, medium rare',
    'das geworfene Handtuch','eine Pfanne mit Zucchini-Feta-Gemüse',
    'mageres Hähnchenbrustfilet','ein Stück Lavendel-Honig-Torte',
    'einen Teller knusprige Kroketten','einen Teller Spargel mit Sauce Hollandaise',
    'Zopfbrot','eine Portion Kimchi, extra scharf','Tteokbokki vom Streetfoodmarkt',
    'einen Teller glitschige Süßkartoffelnudeln','eine extra große Pizza mit Paprika',
    'eine Portion Bangers and Mash','einen Donut mit Ahornsirup und Speck',
    'einen Teller Moussaka','ein großes Stück Red-Velvet-Kuchen',
    'eine Portion Pelmeni mit Schmand','eine dampfende Pfanne Paella',
    'ein knuspriges Langos mit Salz und Öl','einen Spieß frisch gebackener Kartoffelchips mit Salz und Essig',
    'eine ganze Ananas','einen prall gefüllten Frühstücksburrito',
    'eine mehr oder weniger gelungene Weihnachtsgans','eine Handvoll getrocknete Früchte',
    'Gemüsestreifen mit Hummus-Dip','Bertie-Botts-Bohnen in den sonderbarsten Geschmacksrichtungen',
    'drei brodelnde Kesselküchlein','eine Schale festklebender Bonbons aus Omas Schrank',
    'Gourmet-Katzenfutter','ein Omelett mit Pilzen und Cheddar','eine Pizza Supreme mit gefülltem Rand',
    'zwei französische Tacos mit algerischer Soße','eine Packung Schokofrösche',
    'eine deliziöse Schüssel Bouillabaisse','ein schmieriges Sandwich mit zu viel Remoulade',
    'ein Hörnchen vom nächsten Bäcker','einen Tuppen Eiscreme und einen Löffel',
    'frisch gebackenes Fladenbrot und Oliven','ein extravagantes Spezialgericht mit Goldblättchen und Trüffel',
    'eine Schale Nachos mit Käsesoße','eine Tüte süßes Popcorn',
    'eine Tüte salziges Popcorn','einen hellblauen Slushie mit Strohhalm',
    'eine übergroße Erdbeere mit Sahnehäubchen',
    'einen großen Teller Fingerfood mit ungünstig platzierten Spießchen',
    'ein fest geschlossenes Glas saure Gurken','ein billiges Zitroneneis am Stiel',
    'eine winzige Portion Ratatouille mit einem einzelnen Strang Schnittlauch oben drauf',
    'einen Kaugummi mit Drei-Gänge-Menü-Geschmack','einen Quadratmeter frisch gemähtes Gras',
    'eine Portion rohe Po-ta-toes (boil\'em, mash\'em, stick\'em in a stew)',
    'eine kleine Schale Honigpudding','eine Portion dreifach frittierte Pommes mit Mayonnaise',
    'einen triefenden Burger','süße Siruptörtchen','eine große Wolke Zuckerwatte',
    'einen Teller Arme-Ritter-Banane','ein perfekt zubereitetes Filet-Wellington',
    'eine Portion Garnelensalat','eine gut pürierte Smoothie-Bowl',
    'einen Corndog','eine Portion welliger Pommes aus dem Schwimmbad-Bistro',
    'eine feine, mit Frischkäse gefüllte, Blätterteigrolle','eine frisch gebackene Kürbispastete',
    'eine schokolierte Birne am Stiel','eine Schale Regenbogeneis mit Kaugummigeschmack',
    'ein Stück Bienenstichkuchen','ein Blech Rosinenfladen',
    'drei Schaumküsse mit verschiedenen Geschmacksrichtungen',
    'ein Stück deftigen Gemüsekuchen','eine Tüte Chiasamen zum Knabbern',
    'eine Tasse Spargelcremesuppe aus der Tüte','dampfende Kartoffelspalten mit Kräuterquark',
    'einen großen Karamelleisbecher','eine Portion gedünstete Weinbergschnecken',
    'einen Teller Spaghettieis mit Erdbeersoße','ein Blech saftiger Brownies','eine teure Hummerspezialität',
    'Käse in einer Mäusefalle','einen Teller Bouletten und grüne Bohnen','eine Portion Bohnen und Zwiebeln',
    'eine Familienpackung Toffifee','eine Schale Süßigkeiten von letztem Halloween',
    'ein saftiges Rinderfilet mit Feigen','ein ganzes Spanferkel','eine kandierte Zwiebel',
    'Reisporridge mit Frühlingszwiebeln','einen Reiskocher und eine Packung Reis',
    'einen deckenhohen Stapel Pfannkuchen und eine Flasche Ahornsirup','einen gegrillten Gemüsespieß',
    'ein Panna Cotta mit Aprikosenkompott','eine knusprige Heuschrecke am Spieß',
    'eine Schale liebevoll geschnittenes Obst','ein halbes Brötchen mit grober Leberwurst',
    'eine täuschend echte Rolle Toilettenpapier, aber es ist Kuchen','eine große Auswahl an Sushi-Spezialitäten und etwas Sojasoße',
    'eine schmackhafte Ingwerwurzel','eine Portion Süßkartoffelpommes mit Mango-Chutney','ein Ticket zum Mond',
    'eine gut abgeschmeckte Portion Kartoffeleintopf','eine Bockwurst mit Ketchup',
    'einen Teller Eisbein mit Sauerkraut','eine Scheibe salzigen Kasseler','eine Portion Schmorgurken',
    'den Kristallschädel','ein unpraktisch hoch belegtes Sandwich','eine Schale kalte Kartoffeln von gestern',
    'das Hologramm eines königlichen Festmahls','eine Tube Astronautennahrung',
    'einen quadratischen Nährstoffwürfel der Zukunft','ein paar aufgeplatzte Wiener Würstchen',
    'ein Körnerbaguette und Heringshäckerle','Hühnersuppe in einer Flasche',
    'eine Scheibe Pumpernickel mit einem hartgekochten Ei','authentisches indisches Curry',
    'eine Schüssel Soup-Soup-Soup','kandierte Früchte am Stiel','ein dänisches Eis mit knackiger Schokohülle',
    'Eiscreme mit Waldmeistergeschmack','ein Päckchen Gummibärchen für die Tapferkeit',
    'die Überreste vom letzten Abendmahl','ein ausgeplündertes Überraschungsei',
    'einen mexikanischen Burrito mit viel zu dicker Tortilla','ein verschmähtes Stück der Krönungsquiche',
    'eine fischförmiges Gebäck mit roter Bohnenfüllung','ein angenagtes Stück Seife',
    'ein dezent angebrütetes Dinosaurierei','einen köstlichen Auberginenauflauf',
    'eine Handvoll hartgekochter Wachteleier','eine türkische Pizza','einen Falafeldöner mit extra Soße',
    'den Plan 9 aus dem Weltall','eine plattgedrückte Mozartkugel','eine 5,25-Zoll-Diskette',
    'einen Teller Pasta Primaverda','eine heiße Ofenkartoffel','eine Pizza mit riesiger Ananasscheibe',
    'eine halbe Pizza frutti-di-mare mit extra Knoblauch','eine krachende Kaisersemmel',
    'eine Packung gebratener Hühnerherzen','einen sofort die Flucht ergreifenden Tausendfüßler',
    'einen riesigen Königsberger Klops mit Kapernfüllung','einen unverständlichen Gruß aus der Küche',
    'ein schokoladiges Miniaturmodell des Sonnensystems mit Pluto als Kirsche','Gold, Weihrauch und Myrrhe',
    'den kulinarischen Epitaph des Küchenchefs','ein halsbrecherisches Stuntmanöver mit klapperndem Geschirr',
    'einen nicht wie die Abbildung auf der Karte aussehenden Burger','einen echten Cheeseburger zum Mitnnehmen',
    'gefälschten Kokoskuchen mit Hornhautraspel','ein Replikat der Fettecke','einen einzelnen karamellisierten Marshmallow',
    'einen seltenen niederländischen Bergkäse','den Nuclear Football mit Gebrauchsanleitung',
    'ein Schokoladentörtchen mit geschmolzenem Kern','eine Partypackung Salzstangen',
    'ein deftig belegtes Laugenbrötchen','zwei Fischfrikadellen mit Tomatensalat','die Reste der gestrigen Grillfeier',
    'in Ketchup ertränkte Pommes','eine Portion Kartoffelstampf mit Zwiebelsoße','eine Portion Lachs in Kräutersud',
    'Kaviar in einer Schale aus purem Gold','die Experimente eines Amateur-Koches',
    'eine Packung der besten Pfadfinderkekse','eine Dose Mais und einen Löffel','Spaghetti mit einer Fertigsoße',
    'Nudeln mit selbstgemachtem Pesto','eine Portion Kartoffeln mit Kohlrabi-Möhren-Gemüse',
    'mit Zitronenpfeffer panierte Dorschfilets','einen Schokobrunnen und eine Schale Obst','ein deftiges Käse-Fondue',
    'ein paar Gottes Zorn hervorrufende Maultaschen','eine mittelgroße Pizza mit Brokkoli und Hähnchenstreifen',
    'zwei dampfende Schnitzel Cordon bleu','hübsch angerichtete Antipasti','ein paar Scheiben Ciabatta mit Bruschetta',
    'eine überreife Banane mit braunen Stellen','einen fruchtigen Salat mit Honigmelone',
    'eine ganze Aloe-Vera-Pflanze im Topf','ein Frühstücks-Abendessen',
    'die abgelaufene Srirachasoße aus dem Kühlschrank','einen Teller nordische Fischsuppe',
    'ein frisches Matjesbrötchen','eine Dose Schwertfisch mit kürzlich abgelaufenem Verfallsdatum',
    'Kartoffelpuffer mit Apfelmus','Spinat mit gummiartigem Rührei','Spinat mit knusprigen Fischstäbchen',
    'eine tickende Taschenuhr','eine einzelne Bertie-Botts-Bohne mit Hundefuttergeschmack',
    'eine Rolle Klebestreifen ohne findbaren Anfang','eine Schale duftender Fenchelsuppe',
    'eine Schale Fertigsalat aus dem Supermarkt','eine Schüssel Nudel-Rosenkohl-Eintopf','eine Schale Wrukeneintopf',
    'eine glasierte Streuselschnecke','ein fruchtiger Mandarinenkuchen mit Teigstreuseln','ein Stück Fantakuchen',
    'ein Stück wolkigen Schokoladenkuchen mit Puderzucker','einige frittierte Quarkbällchen',
    'eine Tüte Mutzen vom Weihnachtsmarkt','knusprige Süßkartoffelpommes','eine Portion überbackenen Fisch',
    'deftigen Eintopf in einem ausgehöhlten Brotlaib','eine Schale gesalzener Chips mit Salsa-Dip',
    'einen Tortilla-Sombrero mit Guacamole-Rand','ein fürstliches Frühstück',
    'einen Korb frischer Croissants mit einer Auswahl an Marmeladen','zwei glasierte Donuts','zwei gefüllte Donuts',
    'zwei mit Senf gefüllte Donuts','einen einzelnen Glückskeks',
    'ein altes Telefon mit Wählscheibe auf einem Silbertablett','eine Packung Minz-Tic-Tacs',
    'eine Waffel mit Schokoladen-Minz-Eiscreme','eine Schale Frozen Joghurt mit zehn verschiedenen Toppings',
    'einen Krabbenburger mit extra Gürkchen','ein Tablett mit Flugzeugessen','einen gemischten Salat mit Radieschen',
    'zwei getoastete Waffeln','Pflaumenkuchen mit Schlagsahne','ein dutzend Kartoffelknödel in Zwiebeltunke',
    'sechs Eimer Kartoffeln','einen Teller kalten Nudelsalat','gefüllte Kartoffeltaschen mit würziger Soße',
    'einen Teller Krokodilragout','eine Schale in Zitronenwasser gewaschener Seeigelzungen mit Wasabi',
    'flambierte Crêpe Suzette','ein komplettes Englisches Frühstück mit Black Pudding',
    'ein Nutellatoast mit Bananenscheiben','eine Portion hervorragend abgeschmecktes Rührei',
    'einen winzigen Muffin, der nicht so weich ist, wie er aussieht','ein Blech Papageienkuchen',
    'eine schief gewachsene gelbe Paprika','zwei gefüllte rote Paprikas','einen Teller weißen Schichtkohl',
    'Jakobsmuscheln mit schwarzem Trüffel und Haselnuss','einen in Miso marinierten und gebackenen schwarzen Kabeljau',
    'klassisch in Bierteig frittierte Fish`n Chips','ein Stilleben aus Wachs','eine Schale ungewürztes Erbsenpüree',
    'ein gegrilltes Hähnchen mit einer würzigen Tomaten-Curry-Soße','eine kaum Licht spendende Waltranfunsel',
    'gedämpfte Miesmuscheln mit knusprigen Pommes','einen Geburtstagskuchen mit zu wenig Kerzen',
    'einen seltsam grünlich schimmernden Leberkäse','eine angebrochene Packung Oreos',
    'ein Krokodil','eine überraschende Wendung der Dinge','eine dramatische Intrige',
    'einen geheimnisvollen Schlüssel unter einer Speiseglocke','einen Rücktrittsbrief des Papstes',
    'ein unlösbares Rätsel','das Leibgericht von Theodore Roosevelt','die Bestellung des Sitznachbarn',
    'ein saftiges Elchsteak mit Rotkohl','eine intergalaktische Spezialität','ein Rezept und passende Zutaten',
    'einen brennenden Dornbusch','ein Fragment der Heiligen Lanze','einen Kuchen ohne Backpulver',
    'ein Stückchen Nusskuchen','ein Stück Karottenkuchen mit Möhrchendeko',
    'eine Portion unterwürzte Maccaroni mit Käse','Roast Beef mit Yorkshire Pudding','eine defekte Spieluhr',
    'die letzte Packung Schokolade','eine auslaufende Schneekugel mit Sprung',
    'das fliegende Spaghettimonster mit extra großen Fleischbällchen','Albert Einsteins Lieblingsessen: Spaghetti',
    'eine Packung Proteinpulver und Wasser','eine Pizza ohne Rand','eine aufgeklappte Calzone',
    'eine Pizza mit ausschließlich Rand','ein Haar in der Suppe','vier Töpfe cremiger Muschelsuppe',
    'eine Portion Rindfleisch und Brokkoli','ein von Javier Milei mit der Motorsäge zurechtgeschnittenes Beefsteak',
    'ein closed-faced Sandwich','ein open-faced Sandwich',
    'einen auslaufenden Kautschukbaum','Sägespäne mit knuspriger Baumrinde','eine gleißend helle Sonne',
    'ein Stück Sägespänekuchen','Lammbraten mit Minzsoße',
    'ein ambitioniertes Trainingsprogramm','einen straffen Tagesplan','einen Teller Englische Scones mit Marmelade',
    'eine Portion Kanadische Poutine','einen Pfälzer Saumagen auf Sauerkraut','eine Packung knusprige Käsestangen',
    'zwei Körbe fettiger Pizzabrötchen','eine Freikarte für einen sich im Niedergang befindenden Zirkus',
    'einen ganzen Baumkuchen','ein Bündel Scheine','einen Fischburger',
    'einen doppelten Hamburger mit extra Käse','einen blinden Handspiegel','Dornröschens Spindel',
    'eine Liste mit Restaurants in der Nähe','die Bremer Stadtmusikanten','ein Töpfchen mit endlosem süßen Brei',
    'ein Stück frische Honigwabe','einen Teller Rote-Beete-Suppe mit saurer Sahne',
    'einen Salzstreuer mit fast abgeschraubtem Deckel','zwölf knusprige Chicken-Wings',
    'ein großes Lachsfilet mit knuspriger Haut','ein fest geschlossenes Glas Mayonnaise',
    'aufgetauten Kuchen vom letzten Jahr','ein Lebkuchenhaus mit eingestürztem Dach','ein Stück Lebkuchen-Kuchen',
    'auf offenem Feuer zubereitetes Bulgogi','den Orden pour le Mérite','eine billige Imitation vom Goldenen Vlies',
    'das bei Alfred Biolek von Blixa Bargeld gekochte Risotto','das legendenumwobene Stück eines italienischen Rinds',
    'einen Rasenziegel','eine Mütze Schlaf','eine Portion Obatzter','eine Raffaello-Torte',
    'einen Tortenheber ohne Torte weit und breit','einen alten ledrigen linken Stiefel','eine Büste von Karl Marx',
    'Kartoffelpüree aus der Tüte','eine ganze Zitrone','ein Schale Elefantencreme',
    'geschichteten Schokopudding mit Waldbeeren','eine Mao-Bibel','zwei Stücke Champignon-Spinat-Lasagne',
    'eine Schale Haferbrei mit Honig','eine Schale Chiapudding mit Mango','eine weiche Birne','eine einzelne Walnuss',
    'eine sich in seinen Haaren verfangene Fledermaus','einen Hauch von Verachtung für die niederen Dinge im Leben',
    'eine Portion Reis mit Hühnerfrikassee','Jasminreis mit gedünstetem Kaisergemüse',
    'ein Brief eines gemeinsamen Feindes','eine Warnung','die Totenmaske des Tutanchamun',
    'einen Brief von Hogwarts in grüner Tinte','drei westafrikanische Kichererbsenfrikadellen',
    'gebackene Bananenbällchen mit Honig','billiges Sushi',
    'eine Auswahl an winterlichen Gebäcken','Sommerrollen mit Teriyaki-Sauce',
    'einen duftenden Bratapfel','dreizehn üppige Zimtschnecken','selbstgemachte Tacos mit Ortega-Soße',
    'eine Schale geriebenen Gouda','überbackenes Toast Hawaii','einige Stücke russischen Zupfkuchen',
    'gezuckerte Krapfen','eine heiße Apfeltasche','eine gigantische knusprige Krokette',
    'einen Teller mit Herzoginkartoffeln','eine Wildbratwurst mit mediterranem Salat','einen verrückten Lodenfreak',
    'ein ganzes Rad Edamer','kaltgestellte Rache','Nudeln mit Tomatensoße und einem Kilo Parmigiano-Reggiano',
    'ein trauriges Huhn im Topf','ein glückliches Huhn im Topf','ein stoisches Huhn im Topf',
    'des Wahnsinns knusprige Beute','eine hastig improvisierte Mahlzeit','ein Lammfilet, medium well,',
    'ein Wildschweinfilet mit blanchierten Bohnen','den Schuh des Manitu',
    'eine Tube Zahnpasta mit Pfefferminzgeschmack','drei einzelne Kartoffelchips',
    'eine Packung Kartoffelchips mit BBQ-Geschmack','Schwammerlsuppe mit Knallpilzen',
    'ein mit Champignons überbackenes Putenfilet','einen Teller Nudeln mit Fenchelcremesoße',
    'eine Portion Spaghetti mit fußballgroßen Hackbällchen','drei Kugeln Cookies`n-Cream-Eis',
    'zwei Stücke Pizza Margherita','einen lang verschollenen Kindheitsfreund','ein modernes Kunstwerk aus Oliven',
    'einen grünlich blubbernden Eintopf im Hexenkessel','drei schimmernde Heilkristalle','einen deftigen Schlammkuchen',
    'eine Auswahl verschiedenster Macarons','eine Dose Tomatensuppe',
    'ein frisches Dresdner Handbrot vom Weihnachtsmarkt','knusprig gebackenen Seitan mit blanchierem Spargel',
    'eine große Portion vegane Gyoza','einen Zauberwürfel aus Gemüsestückchen','ein deckenhoch gestapeltes Sandwich',
    'zwei vegane Kohlrouladen','ein Stück knusprig-schokoladigen kalten Hund',
    'elegant gerollte Pfannkuchen mit Nutella','elegant gerollte süße Eierkuchen',
    'elegant gerollten, deftigen Palatschinken','elegant gerollte Plinsen mit Apfelmus','drei bunte Mochi am Stiel',
    'die falsche Bestellung','die falsche Rechnung','ein Koreanisches BBQ mit vierzig Nebengerichten',
    'mundgerechte Lachs-Creme-Röllchen mit Dill','lauwarmen Kichererbsensalat',
    'eine Dose Kidneybohnen und einen Löffel','Shoyu-Ramen mit Pok Choi','eine Neuheit aus der modernen Molekularküche',
    'ein Fünf-Sterne-Gericht und eine Lupe','ofengebackenen Wildlachs mit Spinathaube und Mandelsplittern',
    'ein halbes Brötchen mit Eiersalat','ein halbes Brötchen mit Mett','ein halbes Brötchen mit Fleischsalat',
    'ein halbes Brötchen mit Auberginencreme','ein halbes Brötchen mit selbstgemachtem Kräuterquark',
    'eine Schale Kräuterquark mit 50% Zwiebeln','ein Toast mit Avocado und Ei',
    'mexikanische Pommes mit Guacamole und gehackten Tomaten','eine Schale Pigs-in-a-Blanket',
    'einige mit Speck umrollte Datteln','einen hervorragend abgeschmeckten klassischen Salat',
    'Schnitzel mit Mischgemüse und Salzkartoffeln','ein überdimensional großes Nougatkissen',
    'türkischen Honig in einer edel verzierten Schale','einen Döner ohne Brot','eine Erbsen-Mayonnaise-Pizza',
    'den halben Kühlschrank','eine tiefgefrorene Packung Rosenkohl','eine ganze Packung Banana-Split und einen Löffel',
    'ein Himbeereis mit weißer Schokoladenhülle','einen Apfel mit einer weißen und einer roten Backe',
    'eine Schale dünne Suppe mit einem unpraktisch klobigen Holzlöffel',
    'ein Tablett mit undefinierbarem Essen aus der Schulkantine','ein drei-Gänge-Menü von Marco Pierre White',
    'einige Schokokekse mit Orangenfüllung','ein einzelnes rohes Hühnerei','eine Einladung zu einer Kochshow',
    'einen Gutschein zu einem Kochkurs für Anfänger','die Wegbeschreibung zum nächsten Supermarkt',
    'eine Tafel vegane Schokolade','eine übergroße Mandarine','einen Laib Marzipanbrot','eine Packung Backpulver',
    'einen Teller Süßkartoffel-Kichererbsen-Curry','zwei dampfende Falafel-Wraps',
    'ein durchgeweichtes Thunfischsandwich','ein paar hartgekochte Eier im Glas mit Schnittlauch obendrauf',
    'ein Schälchen mit Kaffeesatz','eine Schale verführerischen Rucola-Kartoffelsalat','eine Packung Wikingerröllchen',
    'einige harte Salzkaramell-Bonbons','Mokka-Eiscreme mit einem klitzebisschen Pistazie',
    'nicht weniger als zwanzig Semmelknödel','einen klobig-klebrigen Proteinriegel','das Antlitz der Fata Morgana',
    'einen dreckigen Deal','ein einschneidendes Erfolgserlebnis','einen Berg fettige Ringelpommes',
    'eine meterlange Gurkenspirale','Nougat in Form von Meeresfrüchten',
    'einen Topf Matzah-Ball-Suppe','einen Laib geflochtenes Challah','eine XXL-Packung Merci',
    'Pekingente mit Hoisin-Sauce',
]


