
essen = ['einen Wirsingeintopf', 'einen Lahmacun', 'eine Portion Kartoffelbrei',
                     'Spinat', 'Astronautenfutter', 'ein Snickers', 'einen Mars-Riegel', 'eine Brezel',
                     'eine Portion Gagh', 'ein Filet Mignon', 'einen Döner', 'ein Teller Spaghetti Bolognese',
                     'ein Teller Spaghetti mit Käsesahnesoße', 'einen Obstteller', 'eine Hand voll Gummibärchen',
                     'ein gummiartiges Hühnchen', 'eine Schale mit Kartoffelchips', 'zwei Käsebrote',
                     'Okonomiyaki', 'zwei Stück Erdbeertorte', 'feuriges Chili con Carne', 'ein fluffiges Rührei',
                     'eine leckere Pizza', 'einen frischen Gurkensalat', 'einen großen Chefsalat',
                     'eine übelriechende Käsesuppe', 'Fischstäbchen und Kartoffelbrei', 'ungarisches Gulasch',
                     'Spaghetti mit Soja-Bolognese', 'ein original französisches Ratatouille', 'einen sahnigen Schokopudding',
                     'arme Ritter', 'einen Festtagsbraten mit Klößen', 'Pommes mit Majo', 'leckeren Kartoffelauflauf',
                     'Krabben-Cocktail', 'einen Toast Hawaii', 'indisches Lamm Curry', 'einen Gyrosteller mit Tsatsiki',
                     'ein Pilz-Risotto', 'ein hart gekochtes Ei', 'vier Pralinen mit Nougatfüllung', 'eine kalte Bockwurst',
                     'ein paar Mini-Frühlingsrollen', 'einen Glückskeks mit dem Spruch \"Du wirst heute nicht satt.\" ',
                     'würziges Kassler mit Sauerkraut', 'ein Schälchen Apfelmus', 'Bratkartoffeln', 'asiatisches Wokgemüse',
                     'einen fruchtigen Lolli', 'einen Teller mit süßem Milchreis', 'eine Lasagne', 'chinesisch gebratene Nudeln',
                     'ein Thunfisch-Baguette', 'fünf mexikanische Tacos', 'einen Blaubeermuffin mit Sahne', 'eine Hand voll alte Erdnüsse',
                     'ein Durianeis am Stiel','eine Mango', 'einen Erdnussbutterriegel',
                     'eine Schachtel Lebkuchen', 'eine Portion Falafel mit Hummus', 'ein feuriges Chilli con Soja',
                     'einen Teller getrocknete Jackfruchtstücke', 'eine Packung Choco-Fresh','ein Teller Spagetti Gorgonzola Sosse',
                     'fein geschnittene Karottenstückchen mit laktosefreiem Frischkäse','ein halbes Grillhuhn',
                     'eine Dose Surströmming','einen Steckerlfisch', 'einen Big King','ein Teller voll Buritos',
                     'eine Portion handgerolltes Sushi','ein Butterbrot', 'eine Schnittlauch Brezel','einen Teller szegediner Gulasch',
                     'eine Portion Avocado Maki','eine Spinatlasagne','ein Teller vegetarisch gefüllte Paprika',
                     'ein Teller gefüllte Zucchini','ein Schinken-Käse-Omlett','ein Chop Suey',
                     'ein großes Stück Turducken','einen Teller Spageti Aglio e Olio','Nudeln mit Pesto',
                     'ein Teller Paella','einen Berg Pfannkuchen','ein Teller Belgische Waffeln mit Schokosoße',
                     'eine Waffel mit Puderzucker', 'Grießbrei mit Amarena Kirschen',
                     'einen Kaiserschmarrn mit Apfelmus', 'Palatschinken mit Marillenmarmelade und Staubzucker',
                     'eine Tüte Maiswaffeln','eine Packung Schoko Keksi'
         ]


