getraenke = ['einen Kaffee','eine Limonade','einen Kakao','einen Tee',
                     'einen Kräutertee','eine Cola',
                     'kaltes Wasser','kalten Eistee','einen Raktajino',
                     'frischen Mate', 'eine Club Mate','ein Glas Gurkenwasser',
                     'einen Apfelsaft','einen Traubensaft',
                     'einen Muckefuck','einen Kiwismoothie', 'einen Spinatsmoothie',
                     'einen Orangensaft','einen Coconut Kiss','ein Glas Milch',
                     'einen Erdbeersmoothie','einen Kirschsaft',
                     'einen Latte Macchiato','eine Tasse heiße Schokolade',
                     'ein Glas Sauerkrautwasser','einen Topf Kinderpunsch',
                     'einen Mango-Melone-Smoothie','ein Glas Hoffnung',
                     'einen frischen Pfefferminztee','eine Eisschokolade',
                     'einen Eiskaffee','einen kalten Milchshake',
                     'eine kalte Afri Cola','einen Sojamilch Milchkaffee',
                     'einen Soja Latte Macchiato',
                     'einen Fraktal Allmachtstrank', 'einen Heiltrank',
                     'einen großen Becher Blumenwasser', 'einen Erdbeershake',
                     'einen Blaubeersmoothie', 'eine Tasse Pfefferminztee',
                     'ein kaltes Spezi', 'eine Tasse Hanftee',
                     'eine Karaffe Sprudelwasser', 
                     'einen kleinen Becher Kirsch-Banane-Nektar',
                     'eine Mio Mio Mate',
                     'eine Fritz!Cola', 'ein Ginger-Ale', 'ein Glas laktosefreie Milch',
                     'einen Lebertran', 'eine Caprisonne',
                     'einen Kürbissaft', 'einen Kefir',
                     'einen Ayran', 'ein Glas Nihilismus', 'eine Sprite', 
                     'eine Fanta', 'einen Purple Flurp',
                     'ein leckeres Wasser', 'einen Robby Bubble', 'ein Glas warme Milch',
                     'ein Glas Schlamm', 'ein Glas Regenwasser', 'ein halbes Glas Kokosnussmilch',
                     'ein Glas Ingwerwasser','eine Tasse lauwarmen Sencha',
                     'ein Glas Chai Latte mit Sojamilch','ein Tässchen kalten Sencha',
                     'einen Cappuccino','eine Tasse Cashew-Milch',
                     'eine Karaffe Hoffnung', 'eine Kanne Zuversicht','ein Glas Zuversicht',
                     'einen Soja-Chai-Latte (Kids Temperature)','eine Flasche Paulaner Spezi',
                     'einen Pappbecher Soja-Kakao','eine Flasche Bionade Holunder',
                     'einen Eiskalten Terere', 'eine Runde Wasser für alle',
                     'einen kalt gezogenen grünen Tee','ein Glas Brackwasser',
                     'einen Pappbecher frischen Kaffee mit Sojamilch','einen Becher des Lieblingsgetränkes',
                     'ein Glas frisch gepressten Traubensaft','ein Glas mit zimmerwarmer Hafermilchschokolade',
                     'einen Bubble Tea in einem billigen Plastikbecher',
                     'eine Tasse Rooibostee', 'einen Rainbow-Cocktail', 'einen Virgin Sunrise',
                     'eine Apfelschorle','einen Birnensaft','einen Mangosaft',
                     'ein Glas Holunderblütensirup', 'eine Sauerkirschlimo', 'ein Glas gefrorenes Wasser',
                     'eine bunte Tasse fairtrade Bohnenkaffee','einen Maracujasaft','ein Glas Luft',
                     'ein Glas fairtrade Limonade','eine Cola Light', 'ein Glas Fanta light',
                     'ein Glas Sprite light', 'ein Glas Spezi light','eine dampfende Tasse Winterpunsch-Tee',
                     'eine bunte Tasse Rooibos Schoko-Chai','eine Tasse Rooibos Chai',
                     'eine Tasse Fencheltee mit Honig'
                ]
