getraenke = [

    'einen Kaffee','eine Limonade','einen Kakao','einen Tee',
    'einen Kräutertee','eine Cola',
    'kaltes Wasser','kalten Eistee','einen Raktajino',
    'frischen Mate','eine Club Mate','ein Glas Gurkenwasser',
    'einen Apfelsaft','einen Traubensaft',
    'einen Muckefuck','einen Kiwismoothie','einen Spinatsmoothie',
    'einen Orangensaft','einen Coconut Kiss','ein Glas Milch',
    'einen Erdbeersmoothie','einen Kirschsaft',
    'einen Latte Macchiato','eine Tasse heiße Schokolade',
    'ein Glas Sauerkrautwasser','einen Topf Kinderpunsch',
    'einen Mango-Melone-Smoothie','ein Glas Hoffnung',
    'einen frischen Pfefferminztee','eine Eisschokolade',
    'einen Eiskaffee','einen kalten Milchshake',
    'eine kalte Afri Cola','einen Sojamilch Milchkaffee',
    'einen Soja Latte Macchiato',
    'einen Fraktal Allmachtstrank','einen Heiltrank',
    'einen großen Becher Blumenwasser','einen Erdbeershake',
    'einen Blaubeersmoothie','eine Tasse Pfefferminztee',
    'ein kaltes Spezi','eine Tasse Hanftee',
    'eine Karaffe Sprudelwasser',
    'einen kleinen Becher Kirsch-Banane-Nektar',
    'eine Mio Mio Mate',
    'eine Fritz!Cola','ein Ginger-Ale','ein Glas laktosefreie Milch',
    'einen Lebertran','eine Caprisonne',
    'einen Kürbissaft','einen Kefir',
    'einen Ayran','ein Glas Nihilismus','eine Sprite',
    'eine Fanta','einen Purple Flurp',
    'ein leckeres Wasser','einen Robby Bubble','ein Glas warme Milch',
    'ein Glas Schlamm','ein Glas Regenwasser','ein halbes Glas Kokosnussmilch',
    'ein Glas Ingwerwasser','eine Tasse lauwarmen Sencha',
    'ein Glas Chai Latte mit Sojamilch','ein Tässchen kalten Sencha',
    'einen Cappuccino','eine Tasse Cashew-Milch',
    'eine Karaffe Hoffnung','eine Kanne Zuversicht','ein Glas Zuversicht',
    'einen Soja-Chai-Latte (Kids Temperature)','eine Flasche Paulaner Spezi',
    'einen Pappbecher Soja-Kakao','eine Flasche Bionade Holunder',
    'einen Eiskalten Terere','eine Runde Wasser für alle',
    'einen kalt gezogenen grünen Tee','ein Glas Brackwasser',
    'einen Pappbecher frischen Kaffee mit Sojamilch','einen Becher des Lieblingsgetränkes',
    'ein Glas frisch gepressten Traubensaft','ein Glas mit zimmerwarmer Hafermilchschokolade',
    'einen Bubble Tea in einem billigen Plastikbecher',
    'eine Tasse Rooibostee','einen Rainbow-Cocktail','einen Virgin Sunrise',
    'eine Apfelschorle','einen Birnensaft','einen Mangosaft',
    'ein Glas Holunderblütensirup','eine Sauerkirschlimo','ein Glas gefrorenes Wasser',
    'eine bunte Tasse fairtrade Bohnenkaffee','einen Maracujasaft','ein Glas Luft',
    'ein Glas fairtrade Limonade','eine Cola Light','ein Glas Fanta light',
    'ein Glas Sprite light','ein Glas Spezi light','eine dampfende Tasse Winterpunsch-Tee',
    'eine bunte Tasse Rooibos Schoko-Chai','eine Tasse Rooibos Chai',
    'eine Tasse Fencheltee mit Honig','eine dampfende Tasse Zimtschneckentee',
    'eine dampfende Tasse gebrannte Mandel Tee','einen Heferlkaffee',
    'eine Tasse Kinderpunsch','einen Heidelbeerslushy','einen Himbeerslushy',
    'einen grüner-Apfel-Slushy','einen Limettenslushy','ein großes Soda-Zitrone',
    'einen warmen Schlaf-Freund-Tee','einen Kessel Hexenzauber-Tee','einen Krug Druidentrank-Tee',
    'eine Flasche schwarze-Johannisbeer gespritzt','einen Krug Weichselsaft',
    'ein Glas stark verdünnten Holunderblütensirup','ein Glas viel zu süßen Holunderblütensirup',
    'ein Glas mit der richtigen Menge Holunderblütensirup','eine Packung rote-Rüben-Saft',
    'einmal alles','einen Bergkräutertee mit Kandiszucker','einen Beerkules-Smoothie',
    'eiskaltes Quellwasser','einen stark entkoffeinierten Kaffee',
    'einen Reismilch-Kakao in einer lustigen Tasse','einen Haselnussmilch-Kakao',
    'einen schwachen Kaffee in einer grummeligen Tasse','einen Süßholzwurzeltee',
    'ein Glas klebrig-süßen Karamellsirup','eine Tasse Milch mit Honig',
    'einen heißen Zwetschkenpunsch','geschmolzenes Softeis','eine Flasche Dreh-und-Trink',
    'eine Kelle wässrige Tomatensoße','ein Fass Glück','einen alkoholfreien Kaiserschmarrn-Punsch',
    'ein Kännchen Guten-Morgen-Tee','ein unpraktisch kleines Tässchen Espresso',
    'einen doppelten Espresso mit zwei Zuckerwürfeln','einen vierfachen Espresso und einen Fallschirm',
    'einen Brombeersaft','ein kühles Glas Limettensaft','ein Glas vegane Erdbeermilch',
    'einen Schokobrunnen','einen alkoholfreien Feigenpunsch'
                          'ein Glas abgestandenes Leitungswasser','eine Handvoll Pfützenwasser',
    'eine Tasse türkischen Apfeltee','ein Glas fruchtigen Lycheesaft','zu sprudeliges Sprudelwasser',
    'eine Tasse russische heiße Schokolade','eine Handvoll geschmolzenen Schnee',
    'ein Glas mit aus der Dose abgetropftem Würstchenwasser','Constanzes pürierte Hoffnungen und Träume',
    'überzogenen grünen Tee','den Heiligen Gral gefüllt mit einer ekligen süßen Kinderlimo',
    'eine Dose flüssiger Gummibärchen, auch genannt “Energy-Drink”','einen Cappuccino mit 80% Schaum',
    'einen Krug ganz reines Wasser','eine Flasche trüben Apfelsaft','ein Glas köstlichen Kohlsmoothie',
    'spritzigen Ginger-Ale','Bottys Tränen','eine Tasse dampfenden Darjeeling mit Kandiszucker',
    'naturtrübes alkoholfreies Bier','Kinderglühwein','Wassermelonenwasser in der Wassermelone',
    'ein Glas Mango-Milchshake aus dem Butler-Kronleuchter','ein Reagenzglas mit fluoreszierender Flüssigkeit',
    'eine Flasche alkoholfreies Butterbier','einen Virgin-Swimming-Pool','eine Phiole mit Veritaserum',
    'eine Phiole mit Vielsafttrank und dem Haar eines Einhorns','eine Phiole Amortentia',
    'ein Glas mit Baum-der-Seelen-Essenz','eine Tasse geschmolzene Schokolade',
    'einen edlen Kelch mit feinstem Leitungswasser','ein Glas kalte Milch','einen kühlen Karottensaft',
    'Wasser mit einem Spritzer Waldmeistersirup','den Geschmack des Meeres in einem einzigen Tropfen',
    'ein Glas frische Milch von Kuhdame Gerda','vierzig Gläser frisch gepressten Orangensaft',
    'einen alkoholfreien Amber-Moon','einen kalten Schokoladenmilchshake mit Sahnehäubchen','eine riesige Tasse Kakao',
    'eine trübe Brühe, die verdächtig viel Ähnlichkeit mit Abwaschwasser hat,','einen gekühlten Americano',
    'einen Frappuccino mit vier verschiedenen Sirups','einen Frappuccino mit Magermilch und extra Sahne',
    'eine kaltgewordene heiße Zitrone','eine Tasse Krümeltee','einen Krug Zitronenwasser mit frischen Minzblättern',
    'hochwertigen Traubensaft in einen Plastikmessbecher','einen Schluck Apfelessig','ein Tal voll Tränen',
    'ein Glas Lebertran (der gute mit Stückchen)','einen Schluck saure Milch','eine Flasche Ahornsirup',
    'einen Shot Sojasoße','einen viel zu starken Kaffee','einen viel zu dünnen Kaffee','ein Glas Mandelmilch',
    'ein Glas Hafermilch','ein Glas abgegossenes Kartoffelwasser','ein Glas mit dicker Bratensoße',
    'einen übersalzten Tomatensaft','eine Kanne Kaffee aus der Nachtschicht',
    'eine Tasse perfekt gezogenen Honigblütentee','ein Kristallglas mit einer edlen hellen Flüssigkeit',
    'ein Kristallglas mit einer edlen dunklen Flüssigkeit','ein Glas fruchtigen Multivitaminsaft',
    'ein Glas Rotbäckchensaft mit extra Eisen','drei Milliliter Erdnussöl','eine Flasche Wasser mit Guavengeschmack',
    'ein Glas Brause mit gefrorenen Beeren','ein Glas spritzige Himbeerbrause','eine intravenöse Kochsalzlösung',
    'einen intravenösen doppelten Espresso','ein Glas verdächtig raschelnden Orangensaft',
    'eine Phiole mit Vitalitätstrank','eine Vase Blumenwasser','ein Glas Bitterlemon','flüssigen goldenen Karamell',
    'ein Glas cremige Honig-Senf-Dill-Soße','erfrischendes Mango-Lassi',
    'einen extra großen Bubble-Tea mit extra großen Tapioka-Kugeln',
    'einen Becher mit einer cremigen Mixtur aus Joghurt und Blue Curacao','einen leicht herben Moro-Blutorangensaft',
    'ein Glas Kolumbische Avena','eine Tasse Tibetischen Buttertee',

]
